[project]
name = "automate-generation-software-description"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lxml>=5.4.0",
    "notebook>=7.4.3",
    "openai>=1.91.0",
    "python-dotenv>=1.1.1",
]
